apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-release
  namespace: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeName: jenkins-pv
